version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'quarterly'
    open-pull-requests-limit: 1
    reviewers:
      - Mathsqrt2
    assignees:
      - Mathsqrt2

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'quarterly'
    open-pull-requests-limit: 1
    reviewers:
      - Mathsqrt2
    assignees:
      - Mathsqrt2
