services:
  ai_host:
    build:
      context: .
      dockerfile: ./Dockerfile.ollama
    container_name: ai_host
    restart: always
    tty: true
    ports:
      - "10000:11434"
    networks:
      - ai_talks_network
  ai_talks_database:
    image: mysql:8.0
    container_name: ai_talks_database
    environment:
      MYSQL_ROOT_PASSWORD: v3ryD1ff1cultP@55w0Rd
      MYSQL_DATABASE: ai_talks
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d/
    networks:
      - ai_talks_network
  ai_talks_adminer:
    image: adminer
    restart: always
    depends_on:
      - ai_talks_database
    ports:
      - 18080:8080
    networks:
      - ai_talks_network
  ai_talks:
    environment:
      API_PORT: 13000
      OLLAMA_HOST: ai_host:11434
      DB_HOST: ai_talks_database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: v3ryD1ff1cultP@55w0Rd
      DB_NAME: ai_talks
      MODEL: gemma3:4b
    build:
      context: .
      dockerfile: ./Dockerfile.app
      target: dev
    working_dir: /app
    networks:
      - ai_talks_network
    depends_on:
      - ai_talks_database
      - ai_talks_adminer
      - ai_host
    volumes:
      - .:/app
    ports:
      - 13000:13000
    command: [ sh, -c, 'npm run start:conversation:dev' ]

networks:
  ai_talks_network:
