export enum StateParam {
    SHOULD_ARCHIVE_LOG = "shouldArchiveLog",
    SHOULD_CONTINUE = "shouldContinue",
    SHOULD_SEND_TO_TELEGRAM = "shouldSendToTelegram",
    SHOULD_DISPLAY_RESPONSE = "shouldDisplayResponse",
    SHOULD_LOG = "shouldLog",
    SHOULD_BROADCAST_ON_WEBSOCKET = "shouldBroadcastOnWebSocket",
    IS_GENERATING_ON_AIR = "isGeneratingOnAir",
    LAST_RESPONDER = "lastResponder",
    ENQUEUED_MESSAGE = "enqueuedMessage",
    USER_MESSAGES_STACK_FOR_BOT_1 = "usersMessagesStackForBot1",
    USER_MESSAGES_STACK_FOR_BOT_2 = "usersMessagesStackForBot2",
    LAST_BOT_MESSAGES = "lastBotMessages",
    CURRENT_MESSAGE_INDEX = "currentMessageIndex",
}